name: Shuttle deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - uses: shuttle-hq/deploy-action@main
      #   with:
      #     deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
      - id: check-repo-is-not-initialized
        run: echo "::set-output name=remote-url::$( git config --get remote.origin.url )"
        shell: bash
      - uses: actions/checkout@v2
        if: ${{ !contains(steps.check-repo-is-not-initialized.outputs.remote-url, github.repository) }}s
      - name: Install shuttle cli
        run: |
          # using cargo-quickinstall because it is faster to get shuttle-cli binary
          cargo install cargo-quickinstall
          cargo quickinstall cargo-shuttle
        shell: bash
      - name: Log into shuttle
        run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_DEPLOY_KEY }} # ${{ inputs.deploy-key }}
        shell: bash
      - name: Deploy to shuttle
        if: ${{ inputs.allow-dirty == false }}
        run: cargo shuttle deploy | awk '!/Database URI.*?$/'
        shell: bash
      - name: Deploy to shuttle
        if: ${{ inputs.allow-dirty != false }}
        run: cargo shuttle deploy --allow-dirty | awk '!/Database URI.*?$/'
        working-directory: ${{ inputs.working-directory }}
        shell: bash